export const SECOND_TO_MILLISECONDS = 1000;
export const MINUTE_TO_SECONDS = 60;
export const HOUR_TO_MINUTES = 60;
export const DAY_TO_HOURS = 24;
export const WEEK_TO_DAYS = 7;
export const MILLISECONDS_IN_A_DAY =
  DAY_TO_HOURS * HOUR_TO_MINUTES * MINUTE_TO_SECONDS * SECOND_TO_MILLISECONDS;